security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # Pas de provider tant que je n'ai pas créé l'entité User
  providers:
    users_in_memory:
      memory: ~   # provider fictif

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall API en mode stateless (REST)
    api:
      pattern: ^/api
      stateless: true
      # (a ajouter jwt: ~ plus tard)

  access_control:
    # Quand y aura l'admin: - { path: ^/api/admin, roles: ROLE_ADMIN }
    - { path: ^/api, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
